# Generated by Django 3.2.12 on 2022-02-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
